config/routes.rb
Cer::Application.routes.draw do
  root 'main#index'

  resources :categories, :only => [:show, :index] do
    resources :series, :only => [:show, :index] do
      resources :goals, :only => [:show, :index]
    end
  end

  resources :items, :only => [:show]
  match 'goals/tags/:id' => 'goals#tags', :via => :get

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/categories_controller.rb
include Categories

class CategoriesController < ApplicationController
  def index
  	not_found unless params[:id]
  end

  def show
    self.index
    @category = Categories.get_category_by_id(params[:id])
    not_found if @category.empty?
    render :template => 'categories/index'
  end
end

app/controllers/goals_controller.rb
include Categories

class GoalsController < ApplicationController
  def index
  	not_found unless params[:id]
  end

  def show
  	self.index
  	g = Categories.get_goal_by_id(params[:category_id], params[:id])
  	not_found if g.empty?
  	render :template => 'goals/goal', :locals => { :g => g, :single => true }
  end

  def tags
  	self.index
  	gs = Categories.get_goals_by_tag_name(params[:id])
  	not_found if gs.empty?
  	render :template => 'goals/goals', :locals => { :gs => gs, :single => false }
  end
end

app/controllers/items_controller.rb
include Items

class ItemsController < ApplicationController
  def index
  	not_found unless params[:id]
  end

  def show
    self.index
    @item = Items.get_item_by_id(params[:id].to_i)
    not_found if @item.empty?
    render :template => 'items/index'
  end
end

app/controllers/main_controller.rb
include Categories

class MainController < ApplicationController
  def index
    @categories = Categories.all_categories
  end
end

app/controllers/series_controller.rb
include Categories

class SeriesController < ApplicationController
  def index; end

  def show
    self.index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/markup_helper.rb
module MarkupHelper
  def button (href, content, klass = '')
    haml_tag :a, content.html_safe, :class => "button-1 #{klass}", :href => href
  end
end

app/views/categories/index.html.haml
- button "/", "&lsaquo; Go back"

.box-theme-1
	.category-container-main.c
		.category-content
			%h2<
				= @category[:name]

				%span.subtle-text
					= "| #{@category[:catch_phrase]}"

			%p
				= @category[:description]

			%h3<
				Series:

			%ul.list-1-icons
				- @category[:series].each do |serie|
					%li.ce-scope

						.c
							%span.icon<
								%img{ :src => image_path(serie[:square_icon]), :alt => serie[:name] }/

							.l-portrait-item
								%h3
									- button "#", "#{serie[:name]} &rsaquo;", 'ce-trigger'

								%p
									= serie[:description]

						.box-theme-1.is-hidden.ce-target

							%ul.list-simple
								- serie[:goals].each do |goal|

									%li
										= goal[:title]

										%a.button-1-inline{ :href => "#{categories_path}/#{@category[:id]}/series/#{serie[:id]}/goals/#{goal[:id]}" }<
											Learn &rsaquo;

		.category-content.omega
			%img{ :src => image_path(@category[:main_image]), :alt => @category[:name] }/

app/views/goals/goal.html.haml
- if single
	- button "#{categories_path}/#{params[:category_id]}", "&lsaquo; Go back"

.box-theme-1

	.box-theme-2

		%h2
			= g[:title]
			%span.subtle-text
				= "Taken by #{g[:users_count]} students."

		%p
			= g[:description]

		%ul.list-tags
			- g[:tags].each do |tag|
				%li
					%a.button-1-inline{ :href => "/goals/tags/#{tag}" }
						= tag

	.box-theme-2
		%ul.list-simple
			%li
				= "Author: " + g[:author][:name]
			%li
				= "Amount of items: " + g[:items_count].to_s
			%li
				= "Amount of sentences: " + g[:sentence_count].to_s

	.box-theme-2
		%p
			TODO #=> render items

app/views/goals/goals.html.haml
- button "/", "&lsaquo; Go back"

- gs.each do |g|
	= render :template => 'goals/goal', :locals => { :g => g, :single => single }

app/views/items/index.html.haml
%h1
	Items!

app/views/layouts/application.html.haml
!!!
%html

    %head
        %title Cerego project
        = stylesheet_link_tag 'screen.css', :media => 'screen, projection'
        = javascript_include_tag 'application.js'

    %body
        #page.static-container
            %header.box-theme-3
                = render :partial => "/partials/header"
            .content.box-theme-2.c
                = yield
            %footer.box-theme-1
                = render :partial => "/partials/footer"

app/views/main/category.html.haml
%a.button-1{ :href => '/'}<
	&lsaquo; Go back

.box-theme-1
	.category-container-main.c
		.category-content
			%h2<
				= @category[:name]

				%span.subtle-text
					= "| #{@category[:catch_phrase]}"

			%p
				= @category[:description]

			%h3<
				Series:

			%ul.list-1-icons
				- @category[:series].each do |serie|
					%li.collapsed_
						.c
							%span.icon<
								%img{ :src => image_path(serie[:square_icon]), :alt => serie[:name] }/

							.l-portrait-item
								%h3
									%a.button-1{ :href => '#'}
										= serie[:name]
										&rsaquo;
								%p
									= serie[:description]

						.box-theme-1.is-hidden_
							hello

		.category-content.omega
			%img{ :src => image_path(@category[:main_image]), :alt => @category[:name] }/

%hr

%pre
	= @category

app/views/main/index.html.haml
%ul.category-list.categories-container.c
	- @categories.each_with_index do |cat, i|
		- omega = i % 2 != 0 ? 'omega' : ''

		%li{ :class => ['category-item', omega]}

			.box-theme-1
				.category-container.c
					.category-content
						%h2
							= cat[:name]

						%p
							= cat[:description]

						- button "#{categories_path}/#{cat[:id]}", 'Explore &rsaquo;'

					.category-content.omega
						%img{ :src => image_path(cat[:icon_image]) }/

app/views/main/series.html.haml
%h1
	Series

app/views/partials/_footer.html.haml
%a{ :href => 'mailto:andre.drougge@gmail.com' }
	andre.drougge@gmail.com

app/views/partials/_header.html.haml
%h1
	Welcome to a Rails project by André Drougge